name: Gerar APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Instalar dependencias
        run: flutter pub get

      - name: Configurar Firebase
        run: cp firebase/android/google-services.json android/app/google-services.json

      - name: Gerar APK
        run: flutter build apk --debug

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: Tudo-Aqui-Macacu-APK
          path: build/app/outputs/flutter-apk/app-debug.apk
